# Generated by Django 4.1.2 on 2022-11-03 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_vape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vape',
            name='owner',
            field=models.CharField(default=datetime.datetime(2022, 11, 3, 3, 23, 48, 796371, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
